version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Listing directories...
      - ls -l # Lista el contenido del directorio actual
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the project...
      - npm run build
      - echo Listing files after build...
      - ls -l # Lista el contenido del directorio actual después de la construcción

  post_build:
    commands:
      - echo Build completed successfully.
      - echo PostBuild Phase
      - aws s3 sync ./dist s3://$S3_BUCKET

artifacts:
  files:
    - '**/*'
  base-directory: dist
